services: 
  app:
    image: liadihome
    container_name: liadiHome
    working_dir: /usr/app
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8060:8060"
    tty: true